config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources     :zoos,            only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resource    :zoo_animals,     only: [:create, :destroy]
    end
    resources     :animals,         only: [:index, :show, :new, :create, :edit, :update]
    resources     :animal_types,    only: [:index, :create, :edit, :update]
    resources     :users,           only: [:index, :show, :edit, :update] do
      resources   :zoo_reviews,     only: [:index, :show, :destroy] do
        resources :review_comments, only: [:destroy]
      end
    end
  end

  scope module: :public do
    root :to                       => 'homes#top'
    get   'home/about'             => 'homes#about'
    get   'users/withdraw_confirm' => 'users#withdraw_confirm'
    patch 'users/withdraw'         => 'users#withdraw'
    get   'users/information'      => 'users#show',   as: 'user'
    get   'users/information/edit' => 'users#edit',   as: 'edit_user'
    patch 'users/information'      => 'users#update', as: 'update_user'
    resources     :animals,         only: [:index, :show]
    resources     :zoos,            only: [:index, :show] do
      resources   :zoo_reviews,     only: [:index, :show, :new, :edit, :create, :destroy, :update] do
        resources :review_comments, only: [:create, :destroy]
      end
    end
    get '/search', to: 'searches#search'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/animal_types_controller.rb
class Admin::AnimalTypesController < ApplicationController
  before_action :authenticate_admin!

  def create
    animal_type = AnimalType.new(animal_type_params)
    animal_type.save
    redirect_to admin_animal_types_path
  end

  def index
    @animal_type = AnimalType.new
    @animal_types = AnimalType.all
  end

  def edit
    @animal_type = AnimalType.find(params[:id])
  end

  def update
    animal_type = AnimalType.find(params[:id])
    if animal_type.update(animal_type_params)
      redirect_to admin_animal_types_path
    else
      render :edit
    end
  end

  private

  def animal_type_params
    params.require(:animal_type).permit(:name)
  end

end

app/helpers/admin/animal_types_helper.rb
module Admin::AnimalTypesHelper
end

app/views/admin/animal_types/_search_animal_type.html.erb
<div class="btn-group d-flex mb-3">
  <% if admin_signed_in? %>
    <%= link_to admin_animals_path, class: "btn btn-light text-dark" do %>
      全て
    <% end %>
    <% animal_types.each do |animal_type| %>
      <%= link_to admin_animals_path(name: animal_type.name), class: "btn btn-light text-dark" do %>
        <%= animal_type.name %>
      <% end %>
    <% end %>
  <% else %>
    <%= link_to animals_path, class: "btn btn-light text-dark" do %>
      全て
    <% end %>
    <% animal_types.each do |animal_type| %>
      <%= link_to animals_path(name: animal_type.name), class: "btn btn-light text-dark" do %>
        <%= animal_type.name %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/admin/animal_types/edit.html.erb
<div class='container pt-5'>
  <div class='row pt-4'>
    <div class="col-3"></div>
    <div class="col-6">
      <%= form_with model: @animal_type, url: admin_animal_type_path, method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :種類名 %>
          <%= f.text_field :name, placeholder: "種類名", class: "form-control" %>
        </div>

        <div class="form-group text-center">
          <%= f.submit "変更を保存", class: "btn btn-success" %>
          <%= link_to '保存せずに戻る', admin_animal_types_path, class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/animal_types/index.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <h3>動物の種類一覧・追加</h3>
    </div>
  </div>

  <%= form_with model: @animal_type, url: admin_animal_types_path do |f| %>
    <div class="row pt-5">
      <div class="col-3"></div>
      <div class="col-1">
        <%= f.label :name, '種類名' %>
      </div>
      <div class="col-2">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="col-1">
        <%= f.submit "新規登録", class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>

  <div class="row pt-4">
    <div class="col-3"></div>
    <div class="col-5">
      <table class="table bg-light">
        <thead class="thead-light">
          <tr>
            <th style="width: 70%;">種類</th>
            <th style="width: 30%;"></th>
          </tr>
        </thead>
        <tbody>
          <% @animal_types.each do |animal_type| %>
            <tr>
              <td><%= animal_type.name %></td>
              <td><%= link_to "編集する", edit_admin_animal_type_path(animal_type), class: 'btn btn-sm btn-success' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>