config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources     :zoos,            only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resource    :zoo_animals,     only: [:create, :destroy]
    end
    resources     :animals,         only: [:index, :show, :new, :create, :edit, :update]
    resources     :animal_types,    only: [:index, :create, :edit, :update]
    resources     :users,           only: [:index, :show, :edit, :update] do
      resources   :zoo_reviews,     only: [:index, :show, :destroy] do
        resources :review_comments, only: [:destroy]
      end
    end
  end

  scope module: :public do
    root :to                       => 'homes#top'
    get   'home/about'             => 'homes#about'
    get   'users/withdraw_confirm' => 'users#withdraw_confirm'
    patch 'users/withdraw'         => 'users#withdraw'
    get   'users/information'      => 'users#show',   as: 'user'
    get   'users/information/edit' => 'users#edit',   as: 'edit_user'
    patch 'users/information'      => 'users#update', as: 'update_user'
    resources     :animals,         only: [:index, :show]
    resources     :zoos,            only: [:index, :show] do
      resources   :zoo_reviews,     only: [:index, :show, :new, :edit, :create, :destroy, :update] do
        resources :review_comments, only: [:create, :destroy]
      end
    end
    get '/search', to: 'searches#search'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many :zoo_animals
  has_many :zoos, through: :zoo_animals
  belongs_to :animal_type
  has_one_attached :image

  validates :image,       presence: true
  validates :name,        presence: true
  validates :animal_type, presence: true
  validates :habitat,     presence: true
  validates :body_length, presence: true
  validates :body_weight, presence: true
  validates :feature,     presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def get_image_fit(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fit: [width, height]).processed
  end

  def get_image_fill(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

end

app/models/animal_type.rb
class AnimalType < ApplicationRecord
  has_many :animals

  validates :name,  presence: true
end

app/controllers/admin/animals_controller.rb
class Admin::AnimalsController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:name].nil?
      @animals = Animal.all
    else
      @animals = AnimalType.find_by(name: params[:name]).animals
    end
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      redirect_to admin_animal_path(@animal)
    else
      render :new
    end
  end

  def show
    @animal = Animal.find(params[:id])
  end

  def edit
    @animal = Animal.find(params[:id])
  end

  def update
    @animal = Animal.find(params[:id])
    if @animal.update(animal_params)
      redirect_to admin_animal_path(@animal)
    else
      render :edit
    end
  end

  private

  def animal_params
    params.require(:animal).permit(:image, :name, :animal_type_id, :habitat, :body_length, :body_weight, :feature)
  end

end

app/helpers/admin/animals_helper.rb
module Admin::AnimalsHelper
end

app/views/admin/animals/edit.html.erb
<div class='container pt-5'>
  <div class="row">
    <div class="col-12">
      <h3 class="text-center">動物情報の編集</h3>
      <% if @animal.errors.any? %>
        <%= @animal.errors.count %>件のエラーが発生しました
        <ul>
          <% @animal.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <div class='row'>
    <div class="col-12">
      <%= form_with model: @animal, url: admin_animal_path(@animal), method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :動物画像 %>
          <%= f.file_field :image, accept: "image/*" %>
        </div>

        <div class="form-group">
          <%= f.label :動物名 %>
          <%= f.text_field :name, placeholder: "ライオン", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :種類 %>
          <%= f.collection_select :animal_type_id, AnimalType.all, :id, :name, include_blank: "選択してください", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :生息地 %>
          <%= f.text_field :habitat, placeholder: "アフリカとインドの一部の草原やまばらな林", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :体長 %>
          <%= f.text_field :body_length, placeholder: "1.6〜2.5ｍ", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :体重 %>
          <%= f.text_field :body_weight, placeholder: "150〜260kg", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :特徴 %>
          <%= f.text_area :feature, rows: 8, placeholder: "子どものころには体に暗褐色の斑点がありますが、10カ月ほどで消えてしまいます。", class: "form-control" %>
        </div>

        <div class="form-group text-center">
          <%= f.submit "変更を保存", class: "btn btn-success" %>
          <%= link_to '保存せずに戻る', admin_animal_path(@animal), class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/animals/index.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-12">
      <%= render "admin/animal_types/search_animal_type", animal_types: AnimalType.all %>
    </div>
  </div>

  <div class="row">
    <div class="col-2">
      <% if params[:name].nil? %>
        <h4 class="mb-4">全ての動物</h4>
      <% else %>
        <h4 class="mb-4"><%= params[:name] %>一覧</h4>
      <% end %>
    </div>
    <div class="col-2">
      <%= link_to "新規登録", new_admin_animal_path, class: "btn btn-success" %>
    </div>
  </div>

  <div class="row">
    <% sorted_animals = @animals.sort_by { |animal| [animal.animal_type.id, animal.id] } %>
    <% sorted_animals.each do |animal| %>
      <div class="col-3 mb-4">
        <div class="card h-100">
          <%= link_to admin_animal_path(animal) do %>
            <%= image_tag animal.get_image_fill(240, 160), class: "card-img-top", alt: animal.name %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title text-center"><%= animal.name %></h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/animals/new.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-12">
      <h3 class="text-center">動物の新規登録</h3>
      <% if @animal.errors.any? %>
        <%= @animal.errors.count %>件のエラーが発生しました
        <ul>
          <% @animal.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <%= form_with model: @animal, url: admin_animals_path do |f| %>
        <div class="form-group">
          <%= f.label :動物画像 %>
          <%= f.file_field :image, accept: "image/*" %>
        </div>

        <div class="form-group">
          <%= f.label :動物名 %>
          <%= f.text_field :name, placeholder: "ライオン", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :種類 %>
          <%= f.collection_select :animal_type_id, AnimalType.all, :id, :name, include_blank: "選択してください", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :生息地 %>
          <%= f.text_field :habitat, placeholder: "アフリカとインドの一部の草原やまばらな林", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :体長 %>
          <%= f.text_field :body_length, placeholder: "1.6〜2.5ｍ", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :体重 %>
          <%= f.text_field :body_weight, placeholder: "150〜260kg", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :特徴 %>
          <%= f.text_area :feature, rows: 8, placeholder: "子どものころには体に暗褐色の斑点がありますが、10カ月ほどで消えてしまいます。", class: "form-control" %>
        </div>

        <div class="form-group text-center">
          <%= f.submit "新規登録", class: "btn btn-success" %>
          <%= link_to '新規登録せずに戻る', admin_animals_path(@animal), class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/animals/show.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-12">
      <%= render "admin/animal_types/search_animal_type", animal_types: AnimalType.all %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 text-center">
      <%= image_tag @animal.get_image_fill(1000, 500), class: "img-fluid" %>
    </div>
  </div>

  <div class="row pt-4">
    <div class="col-12 text-center">
      <h2><%= @animal.name %></h2>
    </div>
  </div>

  <div class="row pt-5">
    <div class="col-12">
      <table class="table">
        <tr>
          <th style="width: 20%;">生息地</th>
          <td><%= @animal.habitat %></td>
        </tr>
        <tr>
          <th style="width: 20%;">体長</th>
          <td><%= @animal.body_length %></td>
        </tr>
        <tr>
          <th style="width: 20%;">体重</th>
          <td><%= @animal.body_weight %></td>
        </tr>
        <tr>
          <th style="width: 20%;">特徴</th>
          <td><%= @animal.feature %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row pt-5">
    <div class="col-12 text-center">
      <%= link_to "編集する", edit_admin_animal_path(@animal), class: "btn btn-success" %>
    </div>
  </div>
</div>