config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources     :zoos,            only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resource    :zoo_animals,     only: [:create, :destroy]
    end
    resources     :animals,         only: [:index, :show, :new, :create, :edit, :update]
    resources     :animal_types,    only: [:index, :create, :edit, :update]
    resources     :users,           only: [:index, :show, :edit, :update] do
      resources   :zoo_reviews,     only: [:index, :show, :destroy] do
        resources :review_comments, only: [:destroy]
      end
    end
  end

  scope module: :public do
    root :to                       => 'homes#top'
    get   'home/about'             => 'homes#about'
    get   'users/withdraw_confirm' => 'users#withdraw_confirm'
    patch 'users/withdraw'         => 'users#withdraw'
    get   'users/information'      => 'users#show',   as: 'user'
    get   'users/information/edit' => 'users#edit',   as: 'edit_user'
    patch 'users/information'      => 'users#update', as: 'update_user'
    resources     :animals,         only: [:index, :show]
    resources     :zoos,            only: [:index, :show] do
      resources   :zoo_reviews,     only: [:index, :show, :new, :edit, :create, :destroy, :update] do
        resources :review_comments, only: [:create, :destroy]
      end
    end
    get '/search', to: 'searches#search'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :zoo_reviews,     dependent: :destroy
  has_many :review_comments, dependent: :destroy

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.nickname = "guestuser"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @zoo_reviews = @user.zoo_reviews
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if  @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      render:edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :is_active)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-12">
      <h3><%= "#{@user.nickname}さんの会員情報編集" %></h3>
    </div>
  </div>

  <div class="row pt-4">
    <div class="col-12">
      <%= form_with model: @user, url: admin_user_path(@user), method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :会員ID %>
          <%= @user.id %>
        </div>

        <div class="form-group">
          <%= f.label :ニックネーム %>
          <%= f.text_field :nickname, placeholder: "ニックネーム", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :メールアドレス %>
          <%= f.text_field :email, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :会員ステータス %>
          <%= f.radio_button :is_active, true, id: "is_active_true" %>
          <%= f.label :is_active_true, "有効" %>
          <%= f.radio_button :is_active, false, id: "is_active_false" %>
          <%= f.label :is_active_false, "退会" %>
        </div>

        <div class="form-group text-center">
          <%= f.submit "変更を保存", class: "btn btn-success" %>
          <%= link_to '保存せずに戻る', admin_user_path(@user.id), class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-3">
      <h3>会員一覧</h3>
    </div>
  </div>

  <div class="row">
    <table class="table bg-light">
      <thead class="thead-light">
        <tr>
          <th>会員ID</th>
          <th>ニックネーム</th>
          <th>メールアドレス</th>
          <th>会員ステータス</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td style="width: 15%;"><%= user.id %></td>
            <td style="width: 20%;">
              <%= link_to admin_user_path(user.id) do %>
                <%= user.nickname %>
              <% end %>
            </td>
            <td style="width: 35%;"><%= user.email %></td>
            <td class="<%= user.is_active ? 'text-success' : 'text-secondary' %> font-weight-bold" style="width: 20%;"><%= user.is_active ? '有効' : '退会' %></td>
            <td style="width: 10%;"><%= link_to "編集する", edit_admin_user_path(user.id), class: "btn btn-sm btn-success" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div>
        <%= link_to '会員一覧へ戻る', admin_users_path, class: "btn btn-success" %>
      </div>
      <h3 class="pt-5"><%= "#{@user.nickname}さんの会員詳細" %></h3>
    </div>
  </div>

  <div class="row">
    <table class="table bg-light">
      <thead class="thead-light">
        <tr>
          <th>会員ID</th>
          <th>ニックネーム</th>
          <th>メールアドレス</th>
          <th>会員ステータス</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="width: 15%;"><%= @user.id %></td>
          <td style="width: 20%;"><%= @user.nickname %></td>
          <td style="width: 35%;"><%= @user.email %></td>
          <td class="<%= @user.is_active ? 'text-success' : 'text-secondary' %> font-weight-bold" style="width: 20%;"><%= @user.is_active ? '有効' : '退会' %></td>
          <td style="width: 10%;"><%= link_to "編集する", edit_admin_user_path(@user.id), class: "btn btn-sm btn-success" %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="row pt-5">
    <div class="col-12">
      <h3><%= "#{@user.nickname}さんのレビュー一覧" %></h3>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <table class="table">
        <thead>
          <tr>
            <th>タイトル</th>
            <th>本文</th>
            <th colspan="2"></th>
          </tr>
        </thead>
        <tbody>
          <% @zoo_reviews.each do |zoo_review| %>
            <tr>
              <th style="width: 30%;">
                <%= link_to zoo_review.title, admin_user_zoo_review_path(@user.id, zoo_review), class: "zoo_review_#{zoo_review.id}" %>
              </th>
              <td>
                <% if zoo_review.body.length <= 100 %>
                  <%= zoo_review.body %>
                <% else %>
                  <%= truncate(zoo_review.body, length: 100) %>
                  <%= link_to "もっと読む", admin_user_zoo_review_path(@user.id, zoo_review) %>
                <% end %>
              </td>
              <td style="width: 15%;"><%= render "public/review_comments/counter", zoo_review: zoo_review %></td>
              <td style="width: 15%;"><%= render "public/zoo_reviews/static_rate", zoo_review: zoo_review %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>