config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources     :zoos,            only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resource    :zoo_animals,     only: [:create, :destroy]
    end
    resources     :animals,         only: [:index, :show, :new, :create, :edit, :update]
    resources     :animal_types,    only: [:index, :create, :edit, :update]
    resources     :users,           only: [:index, :show, :edit, :update] do
      resources   :zoo_reviews,     only: [:index, :show, :destroy] do
        resources :review_comments, only: [:destroy]
      end
    end
  end

  scope module: :public do
    root :to                       => 'homes#top'
    get   'home/about'             => 'homes#about'
    get   'users/withdraw_confirm' => 'users#withdraw_confirm'
    patch 'users/withdraw'         => 'users#withdraw'
    get   'users/information'      => 'users#show',   as: 'user'
    get   'users/information/edit' => 'users#edit',   as: 'edit_user'
    patch 'users/information'      => 'users#update', as: 'update_user'
    resources     :animals,         only: [:index, :show]
    resources     :zoos,            only: [:index, :show] do
      resources   :zoo_reviews,     only: [:index, :show, :new, :edit, :create, :destroy, :update] do
        resources :review_comments, only: [:create, :destroy]
      end
    end
    get '/search', to: 'searches#search'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many :zoo_animals
  has_many :zoos, through: :zoo_animals
  belongs_to :animal_type
  has_one_attached :image

  validates :image,       presence: true
  validates :name,        presence: true
  validates :animal_type, presence: true
  validates :habitat,     presence: true
  validates :body_length, presence: true
  validates :body_weight, presence: true
  validates :feature,     presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def get_image_fit(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fit: [width, height]).processed
  end

  def get_image_fill(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

end

app/models/animal_type.rb
class AnimalType < ApplicationRecord
  has_many :animals

  validates :name,  presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
  belongs_to :user
  belongs_to :zoo_review

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :zoo_reviews,     dependent: :destroy
  has_many :review_comments, dependent: :destroy

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.nickname = "guestuser"
    end
  end
end

app/models/zoo.rb
class Zoo < ApplicationRecord
  has_many :zoo_animals, dependent: :destroy
  has_many :zoo_reviews, dependent: :destroy
  has_many :animals,     through: :zoo_animals
  has_one_attached :image

  validates :image,            presence: true
  validates :name,             presence: true
  validates :description,      presence: true
  validates :region,           presence: true
  validates :address,          presence: true
  validates :opening_hours,    presence: true
  validates :closing_day,      presence: true
  validates :admission,        presence: true
  validates :telephone_number, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def get_image_fit(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fit: [width, height]).processed
  end

  def get_image_fill(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end
end

app/models/zoo_animal.rb
class ZooAnimal < ApplicationRecord
  belongs_to :zoo
  belongs_to :animal
end

app/models/zoo_review.rb
class ZooReview < ApplicationRecord
  belongs_to :user
  belongs_to :zoo
  has_many :review_comments, dependent: :destroy

  validates :title, presence: true
  validates :body,  presence: true
  validates :rate,  presence: true

  def self.search_for(content, method)
    if method == 'partial'
      ZooReview.where('title LIKE ? OR body LIKE ?', "%#{content}%", "%#{content}%")
    else
      ZooReview.where('title = ? OR body = ?', content, content)
    end
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
  end
end

app/controllers/admin/zoos_controller.rb
class Admin::ZoosController < ApplicationController
  before_action :authenticate_admin!

  def index
    @zoos = Zoo.all
  end

  def new
    @zoo = Zoo.new
  end

  def create
    @zoo = Zoo.new(zoo_params)
    if @zoo.save
      redirect_to admin_zoo_path(@zoo)
    else
      render :new
    end
  end

  def show
    @zoo = Zoo.find(params[:id])
    @animals = Animal.all
    @zoo_animals = ZooAnimal.where(zoo_id: @zoo.id)
  end

  def edit
    @zoo = Zoo.find(params[:id])
  end

  def update
    @zoo = Zoo.find(params[:id])
    if @zoo.update(zoo_params)
      redirect_to admin_zoo_path(@zoo)
    else
      render :edit
    end
  end

  def destroy
    @zoo = Zoo.find(params[:id])
    @zoo.destroy
    redirect_to admin_zoos_path
  end

  private

  def zoo_params
    params.require(:zoo).permit(:image, :name, :description, :region, :address, :opening_hours, :closing_day, :admission, :telephone_number)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :is_active])
  end
end

app/helpers/admin/animal_types_helper.rb
module Admin::AnimalTypesHelper
end

app/helpers/admin/animals_helper.rb
module Admin::AnimalsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin/zoo_animals_helper.rb
module Admin::ZooAnimalsHelper
end

app/helpers/admin/zoo_reviews_helper.rb
module Admin::ZooReviewsHelper
end

app/helpers/admin/zoos_helper.rb
module Admin::ZoosHelper
  def regions_for_select
    [
      "北海道",
      "東北",
      "関東",
      "中部",
      "近畿",
      "中国",
      "四国",
      "九州",
      "沖縄"
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="pt-5">
  <nav class="navbar navbar-light d-flex justify-content-center" style="background-color: #ffea85;">
    <p class="m-0">Copyright © 2023 ZooNavi Portfolio</p>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-light" style="background-color: #ffea85;">
    <% if admin_signed_in? %>
      <div><%= image_tag "logo.png", style: "width: 100px; height: 50px; object-fit: cover;" %></div>
    <% elsif user_signed_in? %>
      <div><%= image_tag "logo.png", style: "width: 100px; height: 50px; object-fit: cover;" %></div>
    <% else %>
      <%= link_to root_path, class: "navbar-brand" do %>
        <div><%= image_tag "logo.png", style: "width: 100px; height: 50px; object-fit: cover;" %></div>
      <% end %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto d-flex align-items-center">
        <% if admin_signed_in? %>
          <li>
            <%= link_to "動物園一覧", admin_zoos_path, class: 'nav-link text-dark btn' %>
          </li>
          <li>
            <%= link_to "動物一覧", admin_animals_path, class: 'nav-link text-dark btn' %>
          </li>
          <li>
            <%= link_to "動物種一覧", admin_animal_types_path, class: 'nav-link text-dark btn' %>
          </li>
          <li>
            <%= link_to "会員一覧", admin_users_path, class: 'nav-link text-dark btn' %>
          </li>
          <li>
            <%= link_to "ZooNaviについて", home_about_path, class: 'nav-link text-dark btn' %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark btn' %>
          </li>
        <% elsif user_signed_in? %>
          <li>
            <%= link_to "動物園一覧", zoos_path, class: 'nav-link text-dark btn' %>
          </li>
          <li>
            <%= link_to "動物一覧", animals_path, class: 'nav-link text-dark btn' %>
          </li>
          <li>
            <%= link_to "マイページ", user_path, class: 'nav-link text-dark btn' %>
          </li>
          <li>
            <%= link_to "ZooNaviについて", home_about_path, class: 'nav-link text-dark btn' %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark btn' %>
          </li>
        <% else %>
          <li>
            <%= link_to "動物園一覧", zoos_path, class: 'nav-link text-dark btn' %>
          </li>
          <li>
            <%= link_to "動物一覧", animals_path, class: 'nav-link text-dark btn' %>
          </li>
          <li>
            <%= link_to "ZooNaviについて", home_about_path, class: 'nav-link text-dark btn' %>
          </li>
          <li>
            <%= link_to "ゲストログイン", users_guest_sign_in_path, class: "nav-link text-dark btn sign_in", method: :post %>
          </li>
          <li>
            <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark btn' %>
          </li>
          <li>
            <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark btn' %>
          </li>
          <li>
            <%= link_to "管理者ログイン", new_admin_session_path, class: 'nav-link text-dark btn' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZooNavi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/3ba50c36e8.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>